in_dir = "n/a"
mask_dir = "n/a"
out_dir = "outputs/e1_35"
width = 512
height = 512
stride = 1

[[keyframes]]
frame = 1
seed = 1291772199
prompt = "neon hieroglyphics intertwined with shiny metal sculpture, onyx, pink, highly detailed, ultra realistic, octane render 8k, by guerrino boatto"
scale = 10.0
strength = 0.5
steps = 50
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [2.0, 0.0]  # pixels per frame for X and Y
animation.rotate = -1.0           # rotations per frame in revolutions (positive is CCW)
correct_colors = true

[[keyframes]]
duration = 100
animation.zoom = 0.98
animation.translate = [0.0, -2.0]
animation.rotate = -0.1

[[keyframes]]
duration = 100
animation.zoom = 1.0
animation.translate = [-5.0, 0.0]
animation.rotate = 0.0

[[keyframes]]
duration = 80
prompt = "neon sculptures, shiny metal statues, background of rugged onyx rocks, highly detailed, ultra realistic, octane render 8k by kilian eng and guerrino boatto"
animation.zoom = 1.02
animation.translate = [0.0, -2.0]
animation.rotate = 1.0

[[keyframes]]
duration = 100
prompt = "shiny obsidian cubic crystals with small embedded glowing emeralds rubies and sapphires, highly detailed, ultra realistic, octane render 8k by kilian eng and guerrino boatto"
